[theme]
base="dark"
primaryColor="#DF36F5"
backgroundColor = "#29252e"
textColor = "#FFFFFF"
font = "sans serif"

[ui]
layout = "wide"

[server]
headless = true
port = 8501
enableCORS = false

[global]
enableCORS = true